name: Taskify
description: On-demand service application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  provider: ^6.1.1
  get_it: ^8.0.3
  injectable: ^2.3.2
  flutter_stripe: ^9.5.0+1
  http: ^1.1.0
  rxdart: ^0.28.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  google_fonts: ^6.1.0
  lottie: ^3.2.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  share_plus: ^10.1.3
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.1
  fl_chart: ^0.69.2
  shared_preferences: ^2.0.13
  geocoding: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
      - lib/assets/animations/service_splash.json
      - lib/assets/images/google.svg
      - lib/assets/images/image1.jpg
      - lib/assets/images/image2.jpg
      - lib/assets/images/image3.jpg
      - lib/assets/images/promo.jpg
      - lib/assets/images/icon.png
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21